# TODO: adding an item at the beginning of a list (things to look after the homework)
# TODO: adding an item in the middle of the list (things to look at after the homework)

# TODO: EXTEND - extend programme to allow user input 6 numbers and it checks if matches random numbers and prints
# message







# TODO: ALTERNATIVE Go through this and check if can do alternative, also with tuples, can have a while loop

#TODO: while loop
# number = 0
# while number < 50:
#     integer = number + 1

# ALTERNATIVE
# one line of code
# created a variable assigned to combined functions list and range
# combined list function and range to directly convert the sequence of numbers by generated by range into a list
# lottery_list = list(range(1, 51))
#
# print(f"lottery numbers: {lottery_list.append(random.randrange(1, 51))}")

# for num in lottery_list:
# display 6 unique random lottery numbers between 1 and 50

# use python help() function to find out which function to use from the python standard library called random
#
# print(lottery_list)
#     lottery_list = random.randrange(1, 51)
#     print(f"lottery numbers: {lottery_list} * 6")
#     # for each iteration of this loop num take on the next value
#     lottery_list.append(num)

#  print(lottery_list)

# ALTERNATIVE (Tuples as they are immutable)
# lottery_tuple = tuple(range(1, 51))
# print(lottery_tuple)


# which python data structure best suited to store the numbers